### ISSUE TITLE
I do not understand how data preloading work for ssr

### ISSUE THREAD

**Issue by rolele** [emilecantin/ssr_code-splitting_sample#2]
Hi, excellent work for the code splitting part.
Now for the ssr part without querying an external api I found it a little dull.
I am having some trouble right now to do it myself or find any example on the internet.
Could you please provide some minor changes showing prefetch data loading on server-side?
Cheers,
Keep up the good work. Thanks.

**Comment by emilecantin** [comment]
Hi @rolele, and thanks for the kind words.

You're absolutely right that this is a difficult part, and I have a blog article in the works that will cover exactly that. Expect it in about a month or so.

**Comment by rolele** [comment]
Please have a look to my work on SSR with Redux and RR4:
https://github.com/rolele/universal-react-redux-boilerplate
You can also see the PR to the original repo (with some comments) here:
https://github.com/CrocoDillon/universal-react-redux-boilerplate/pull/25

I think I am very close to have a very good solution following all the best recommendations I could find on all the documentations but I am still facing some issues that I describe in the PR.

I think this work is very close to your next blog article about SSR so you might be interested in reviewing it and I will be interested in having any suggestions on how to solve my issues.
Thanks
