### ISSUE TITLE
SEO-friendly URLs

### ISSUE THREAD

**Issue by serhiizelinsky** [emilecantin/ssr_code-splitting_sample#4]
Hi, there.

I have collapsed with a similar problem. I need server-side rendering, code-splitting and etc. I have approximately 10 different pages in my SPA. Application uses SEO-friendly URLs. Mappings between URLs and routes are stored in database.

For example:
URL: `/apartments-for-sale-new-york`
route: `/search/index`
or
URL: `/apartments-for-sale-new-york-royal-street-4`
route: `/apartment/index`
or
URL: `/apartments-for-sale-streets-of-new-york`
route: `/list/streets`

So, I need to fetch route by URL, and use route for resolving component in my application. We haven't `getComponent` in updated version of react-router and I don't know to resolve this issue.

How can I do it on both client and server side?

Thanks.

**Comment by serhiizelinsky** [comment]
@emilecantin, could you help me, please.

**Comment by emilecantin** [comment]
You'll need a component that renders the appropriate component depending on your route mapping.

This isn't on-topic for this repo, though, so I'll go ahead and close the issue.
